server {
    listen 3000;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }

    location /_next {
        root /usr/share/nginx/html;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }
}
