{
  "version": "3.8",
  "services": {
    "postgres": {
      "ports": [
        "5432:5432"
      ]
    },
    "frontend": {
      "ports": [
        "3000:3000"
      ]
    },
    "ollama": {
      "ports": [
        "11434:11434"
      ]
    },
    "redis": {
      "ports": [
        "6379:6379"
      ]
    },
    "backend": {
      "ports": [
        "8000:8000"
      ]
    }
  }
}
