'use client'

import { useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ArrowLeft, TrendingUp, TrendingDown, Zap, RefreshCw, Activity, Shield, Database, Cpu, BarChart3, PieChart } from 'lucide-react'
import {
  AreaChart, Area, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar,
  XAxis, YAxis, Tooltip, ResponsiveContainer,
} from 'recharts'
import { STOCKS, priceMap, T, fI, pct } from '@/lib/stockData'

const card = (x = {}) => ({ background: T.card, border: `1px solid ${T.b}`, borderRadius: 10, ...x })
const sc = v => v >= 70 ? T.green : v >= 45 ? T.amber : T.red

function Badge({ v }) {
  const c = sc(v)
  return <span style={{ background: `${c}22`, color: c, border: `1px solid ${c}44`, borderRadius: 4, padding: '2px 9px', fontSize: 12, fontFamily: T.mono, fontWeight: 700 }}>{v}</span>
}

function Tag({ children, color = '#a78bfa' }) {
  return <span style={{ background: `${color}22`, color, border: `1px solid ${color}44`, borderRadius: 4, padding: '2px 7px', fontSize: 10, fontWeight: 700 }}>{children}</span>
}

function FactorBar({ label, value }) {
  return (
    <div style={{ marginBottom: 9 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 3 }}>
        <span style={{ fontSize: 11, color: T.sub }}>{label}</span>
        <span style={{ fontSize: 11, fontFamily: T.mono, fontWeight: 700, color: sc(value) }}>{value}</span>
      </div>
      <div style={{ height: 5, background: T.b, borderRadius: 3, overflow: 'hidden' }}>
        <div style={{ height: '100%', width: `${value}%`, borderRadius: 3, background: 'linear-gradient(90deg,#f43f5e,#f59e0b,#22c55e)' }} />
      </div>
    </div>
  )
}

function CT({ active, payload, label }: { active?: any; payload?: any; label?: any } = {}) {
  if (!active || !payload?.length) return null
  return (
    <div style={{ background: T.el, border: `1px solid ${T.b}`, borderRadius: 6, padding: '8px 12px', fontSize: 12 }}>
      <div style={{ color: T.muted, marginBottom: 4 }}>{label}</div>
      {payload.map((p, i) => (
        <div key={i} style={{ color: p.color || T.text, fontFamily: T.mono }}>
          {typeof p.value === 'number' ? p.value.toFixed(2) : p.value}
        </div>
      ))}
    </div>
  )
}

const OLLAMA_URL = 'http://localhost:11434/api/chat'
const OLLAMA_MODEL = 'llama3.2'

async function callOllama(messages, system) {
  const res = await fetch(OLLAMA_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: OLLAMA_MODEL,
      messages: [{ role: 'system', content: system }, ...messages],
      stream: false,
      options: { temperature: 0.4 },
    }),
  })
  if (!res.ok) throw new Error('Ollama unreachable')
  const d = await res.json()
  return d.message?.content || ''
}

function buildOfflineReport(s) {
  const tier = v => v >= 70 ? 'top-tier' : v >= 45 ? 'mid-tier' : 'lower-tier'
  const peers = STOCKS.filter(x => x.sector === s.sector && x.ticker !== s.ticker).sort((a, b) => b.composite - a.composite).slice(0, 2)
  return `**Quick Snapshot**
${s.name} (${s.ticker}) trades at ₹${s.price.toLocaleString('en-IN')} (${pct(s.chg)} today) with a P/E of ${s.pe.toFixed(1)}x and ROE of ${s.roe.toFixed(1)}%. Its composite factor score of ${s.composite}/100 places it in the ${tier(s.composite)} of the Nifty universe within ${s.sector}.

**Strengths**
• ${s.qual >= 65 ? `Strong Quality score (${s.qual}) — ROE of ${s.roe.toFixed(1)}% signals efficient capital use` : `Revenue growing at ${s.rev.toFixed(1)}% YoY, a reasonable pace for ${s.sector}`}
• ${s.mom >= 65 ? `Momentum score of ${s.mom} shows strong recent relative price strength` : `Valuation looks measured at ${s.pe.toFixed(1)}x earnings`}
• ${s.val >= 55 ? `Value score of ${s.val} suggests the stock isn't expensive relative to peers` : `Established scale within the ${s.sector} sector (composite rank: ${s.composite})`}

**Risks**
• ${s.pe > 40 ? `P/E of ${s.pe.toFixed(1)}x is elevated — leaves limited room for multiple expansion` : `Momentum score of ${s.mom} is muted — limited near-term price catalysts visible in the data`}
• ${s.pb > 10 ? `P/B of ${s.pb.toFixed(1)}x implies the market is pricing in a lot of future growth` : `Growth score of ${s.grw} suggests topline momentum could be inconsistent quarter to quarter`}

**Factor View**
A composite score of ${s.composite}/100 (Momentum ${s.mom} · Quality ${s.qual} · Value ${s.val} · Growth ${s.grw}) places ${s.ticker} in the ${tier(s.composite)} of its peer set on a blended multi-factor basis.

**Peers**
${peers.length ? peers.map(p => `${p.ticker} (composite ${p.composite})`).join(' · ') : 'No close sector peers in this sample universe.'}

⚠️ Generated by QuantAI's offline rule-based engine (no LLM call — Ollama not reachable). Self-host this app with Ollama running locally for full open-source LLM-generated analysis. Educational purposes only — not investment advice.`
}

export default function StockDetail() {
  const params = useParams()
  const router = useRouter()
  const ticker = (params.ticker as string).toUpperCase()
  const stock = STOCKS.find(s => s.ticker === ticker)

  const [aiText, setAiText] = useState('')
  const [aiLoad, setAiLoad] = useState(false)
  const [aiSource, setAiSource] = useState<string | null>(null)

  if (!stock) {
    return (
      <div style={{ padding: '26px 30px', maxWidth: 1200, fontFamily: T.sans }}>
        <div style={{ textAlign: 'center', padding: 40, color: T.muted, fontSize: 14 }}>
          Stock <strong>{ticker}</strong> not found in the Nifty 500 universe.
        </div>
      </div>
    )
  }

  const pts = priceMap[stock.ticker] || []
  const radar = [
    { f: 'Momentum', v: stock.mom },
    { f: 'Quality', v: stock.qual },
    { f: 'Value', v: stock.val },
    { f: 'Growth', v: stock.grw },
    { f: 'Composite', v: stock.composite },
  ]

  async function getAI() {
    setAiLoad(true)
    setAiText('')
    setAiSource(null)
    const prompt = `Analyze ${stock.name} (${stock.ticker}, NSE):
Price: ₹${stock.price} | 1-Day: ${pct(stock.chg)} | Sector: ${stock.sector} | MCap: ₹${stock.mcap}K Cr
PE: ${stock.pe}x | PB: ${stock.pb}x | ROE: ${stock.roe}% | Revenue Growth: ${stock.rev}%
Factor Scores (0-100): Momentum ${stock.mom} · Quality ${stock.qual} · Value ${stock.val} · Growth ${stock.grw} · Composite ${stock.composite}

Provide:
**Quick Snapshot** (2-3 sentences on what metrics reveal)
**Strengths** (top 3 quantitative positives)
**Risks** (top 2 risks from data)
**Factor View** (what composite score of ${stock.composite}/100 means in ${stock.sector} context)
**Peers** (1-2 comparable NSE stocks to benchmark against)`

    try {
      const text = await callOllama(
        [{ role: 'user', content: prompt }],
        'You are a quantitative equity analyst specializing in Indian NSE/BSE stocks. Provide structured, data-driven analysis. Format clearly with headers. End with: ⚠️ Educational purposes only — not investment advice.'
      )
      setAiText(text)
      setAiSource('ollama')
    } catch {
      setAiText(buildOfflineReport(stock))
      setAiSource('offline')
    }
    setAiLoad(false)
  }

  return (
    <div style={{ padding: '26px 30px', maxWidth: 1200, fontFamily: T.sans }}>
      <button
        onClick={() => router.push('/screener')}
        style={{ background: 'none', border: 'none', color: T.muted, cursor: 'pointer', fontSize: 12, marginBottom: 10, padding: 0 }}
      >
        ← Back to Screener
      </button>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 22 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div
            style={{
              width: 46, height: 46, background: `${T.blue}33`, borderRadius: 10,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: 13, fontWeight: 700, fontFamily: T.mono, color: T.blue,
            }}
          >
            {stock.ticker.slice(0, 2)}
          </div>
          <div>
            <div style={{ fontSize: 22, fontWeight: 700, color: T.text }}>
              {stock.ticker} <span style={{ fontSize: 13, color: T.muted, fontWeight: 400 }}>· {stock.name}</span>
            </div>
            <div style={{ display: 'flex', gap: 8, marginTop: 4 }}>
              <Tag>{stock.sector}</Tag>
              <Tag color={T.blue}>NSE Listed</Tag>
            </div>
          </div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <div style={{ fontSize: 28, fontWeight: 700, fontFamily: T.mono, color: T.text }}>
            ₹{stock.price.toLocaleString('en-IN')}
          </div>
          <div style={{ fontSize: 14, fontFamily: T.mono, color: stock.chg >= 0 ? T.green : T.red }}>
            {stock.chg >= 0 ? '\u25B2' : '\u25BC'} {Math.abs(stock.chg).toFixed(2)}%
          </div>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 280px', gap: 14, marginBottom: 14 }}>
        <div style={card({ padding: '16px 18px' })}>
          <div style={{ fontSize: 13, fontWeight: 600, color: T.text, marginBottom: 14 }}>Price History (6M)</div>
          <ResponsiveContainer width="100%" height={195}>
            <AreaChart data={pts} margin={{ top: 4, right: 4, bottom: 0, left: 50 }}>
              <defs>
                <linearGradient id="sg" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor={stock.chg >= 0 ? T.green : T.red} stopOpacity={0.3} />
                  <stop offset="95%" stopColor={stock.chg >= 0 ? T.green : T.red} stopOpacity={0} />
                </linearGradient>
              </defs>
              <XAxis dataKey="d" tick={{ fontSize: 10, fill: T.muted }} tickLine={false} axisLine={false} interval={15} />
              <YAxis
                tick={{ fontSize: 10, fill: T.muted, fontFamily: T.mono }}
                tickLine={false} axisLine={false} domain={['auto', 'auto']}
                tickFormatter={v => '₹' + v.toLocaleString('en-IN')}
              />
              <Tooltip content={<CT />} />
              <Area type="monotone" dataKey="p" stroke={stock.chg >= 0 ? T.green : T.red} strokeWidth={2} fill="url(#sg)" dot={false} />
            </AreaChart>
          </ResponsiveContainer>
        </div>

        <div style={card({ padding: '16px 14px' })}>
          <div style={{ fontSize: 13, fontWeight: 600, color: T.text, marginBottom: 4 }}>Factor Profile</div>
          <ResponsiveContainer width="100%" height={190}>
            <RadarChart data={radar}>
              <PolarGrid stroke={T.b} />
              <PolarAngleAxis dataKey="f" tick={{ fontSize: 10, fill: T.muted }} />
              <PolarRadiusAxis angle={90} domain={[0, 100]} tick={false} axisLine={false} />
              <Radar dataKey="v" stroke={T.blue} fill={T.blue} fillOpacity={0.18} strokeWidth={2} />
            </RadarChart>
          </ResponsiveContainer>
          <div style={{ textAlign: 'center', marginTop: 4 }}><Badge v={stock.composite} /></div>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
        <div style={card({ padding: '16px 18px' })}>
          <div style={{ fontSize: 13, fontWeight: 600, color: T.text, marginBottom: 14 }}>Fundamentals</div>
          {[
            ['P/E Ratio', stock.pe.toFixed(1) + 'x', stock.pe < 30 ? T.green : stock.pe < 60 ? T.amber : T.red],
            ['P/B Ratio', stock.pb.toFixed(1) + 'x', stock.pb < 4 ? T.green : stock.pb < 10 ? T.amber : T.red],
            ['ROE', stock.roe.toFixed(1) + '%', stock.roe > 18 ? T.green : stock.roe > 10 ? T.amber : T.red],
            ['Revenue Growth', stock.rev.toFixed(1) + '%', stock.rev > 15 ? T.green : stock.rev > 7 ? T.amber : T.red],
            ['Market Cap', '₹' + stock.mcap + 'K Cr', T.text],
            ['Sector', stock.sector, T.text],
          ].map(([l, v, c]) => (
            <div key={l} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: `1px solid ${T.b}` }}>
              <span style={{ fontSize: 12, color: T.sub }}>{l}</span>
              <span style={{ fontSize: 12, fontFamily: T.mono, fontWeight: 600, color: c }}>{v}</span>
            </div>
          ))}
          <div style={{ marginTop: 16 }}>
            {[['Momentum', stock.mom], ['Quality', stock.qual], ['Value', stock.val], ['Growth', stock.grw]].map(([l, v]) => (
              <FactorBar key={l} label={l} value={v} />
            ))}
          </div>
        </div>

        <div style={card({ padding: '16px 18px', display: 'flex', flexDirection: 'column' })}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
            <div style={{ fontSize: 13, fontWeight: 600, color: T.text }}>AI Research Summary</div>
            <button
              onClick={getAI}
              disabled={aiLoad}
              style={{
                display: 'flex', alignItems: 'center', gap: 6, background: T.blue, border: 'none',
                borderRadius: 6, padding: '7px 13px', fontSize: 12, color: '#fff',
                cursor: aiLoad ? 'not-allowed' : 'pointer', opacity: aiLoad ? 0.6 : 1,
              }}
            >
              <Zap size={12} />{aiLoad ? 'Analyzing…' : 'Generate AI Report'}
            </button>
          </div>
          {aiSource && (
            <div style={{ marginBottom: 8 }}>
              <Tag color={aiSource === 'ollama' ? T.green : T.amber}>
                {aiSource === 'ollama' ? '⚡ Ollama (local LLM)' : '📐 Offline Engine'}
              </Tag>
            </div>
          )}
          <div style={{ flex: 1, overflowY: 'auto', fontSize: 12, color: T.text, lineHeight: 1.75, minHeight: 280 }}>
            {!aiText && !aiLoad && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: 10, color: T.muted }}>
                <Zap size={28} color={T.blue} style={{ opacity: 0.4 }} />
                <div style={{ textAlign: 'center', fontSize: 12 }}>
                  <div style={{ color: T.sub, marginBottom: 4 }}>Free, Open-Source AI Research</div>
                  <div>Tries your self-hosted Ollama instance first, falls back to an offline rule-based engine — zero cost either way.</div>
                </div>
              </div>
            )}
            {aiLoad && (
              <div style={{ color: T.muted, display: 'flex', alignItems: 'center', gap: 8, fontSize: 12 }}>
                <RefreshCw size={13} style={{ animation: 'spin 1s linear infinite' }} /> Analyzing {stock.ticker}…
              </div>
            )}
            {aiText && <div style={{ whiteSpace: 'pre-wrap' }}>{aiText}</div>}
          </div>
        </div>
      </div>
    </div>
  )
}
